import { Ticket } from './types';

export const mockTickets: Ticket[] = [
  {
    id: 'TKT-001',
    subject: 'Cannot login to my account',
    customer: { name: 'Alice Johnson', avatarUrl: 'https://placehold.co/32x32/E9D5FF/4C1D95?text=AJ' },
    assignedTo: 'John Doe',
    status: 'Open',
    priority: 'High',
    createdAt: '2024-07-10T10:00:00Z',
    lastUpdate: '2024-07-10T10:05:00Z',
    conversation: [
        {
            id: 'msg-1',
            author: 'Alice Johnson',
            avatarUrl: 'https://placehold.co/32x32/E9D5FF/4C1D95?text=AJ',
            text: "Hi, I'm having trouble logging into my account. I've tried resetting my password but the link seems to be expired. Can you help?",
            timestamp: '2024-07-10T10:00:00Z',
            type: 'public',
        },
        {
            id: 'msg-2',
            author: 'John Doe',
            avatarUrl: 'https://placehold.co/40x40/E9D5FF/4C1D95?text=JD',
            text: 'Hi Alice, I\'ve sent a new password reset link to your email. Please let me know if you still have issues.',
            timestamp: '2024-07-10T10:05:00Z',
            type: 'public',
        },
        {
            id: 'msg-3',
            author: 'John Doe',
            avatarUrl: 'https://placehold.co/40x40/E9D5FF/4C1D95?text=JD',
            text: 'User seems to be on an older version of the app, might be the cause of the expired links.',
            timestamp: '2024-07-10T10:06:00Z',
            type: 'internal',
        }
    ]
  },
  {
    id: 'TKT-002',
    subject: 'Website is loading very slowly',
    customer: { name: 'Bob Williams', avatarUrl: 'https://placehold.co/32x32/A7F3D0/064E3B?text=BW' },
    assignedTo: 'Jane Smith',
    status: 'In Progress',
    priority: 'Medium',
    createdAt: '2024-07-09T14:30:00Z',
    lastUpdate: '2024-07-10T09:15:00Z',
    conversation: [],
  },
  // ... other tickets remain the same but would also have conversation arrays
  {
    id: 'TKT-003',
    subject: 'Billing inquiry: incorrect charge',
    customer: { name: 'Charlie Brown', avatarUrl: 'https://placehold.co/32x32/FEE2E2/991B1B?text=CB' },
    assignedTo: 'John Doe',
    status: 'Open',
    priority: 'High',
    createdAt: '2024-07-10T08:45:00Z',
    lastUpdate: '2024-07-10T08:45:00Z',
    conversation: [],
  },
  {
    id: 'TKT-004',
    subject: 'Feature request: dark mode',
    customer: { name: 'Diana Prince', avatarUrl: 'https://placehold.co/32x32/BFDBFE/1E3A8A?text=DP' },
    assignedTo: 'Unassigned',
    status: 'Open',
    priority: 'Low',
    createdAt: '2024-07-08T11:00:00Z',
    lastUpdate: '2024-07-08T11:00:00Z',
    conversation: [],
  },
  {
    id: 'TKT-005',
    subject: 'Password reset link not working',
    customer: { name: 'Ethan Hunt', avatarUrl: 'https://placehold.co/32x32/FEF08A/854D0E?text=EH' },
    assignedTo: 'Jane Smith',
    status: 'Closed',
    priority: 'Medium',
    createdAt: '2024-07-07T16:20:00Z',
    lastUpdate: '2024-07-08T10:00:00Z',
    conversation: [],
  },
    {
    id: 'TKT-006',
    subject: 'API integration issue',
    customer: { name: 'Fiona Glenanne', avatarUrl: 'https://placehold.co/32x32/FBCFE8/86198F?text=FG' },
    assignedTo: 'John Doe',
    status: 'In Progress',
    priority: 'High',
    createdAt: '2024-07-10T11:00:00Z',
    lastUpdate: '2024-07-10T11:30:00Z',
    conversation: [],
  },
  {
    id: 'TKT-007',
    subject: 'How to update my profile?',
    customer: { name: 'George Costanza', avatarUrl: 'https://placehold.co/32x32/D1FAE5/065F46?text=GC' },
    assignedTo: 'Support Bot',
    status: 'Closed',
    priority: 'Low',
    createdAt: '2024-07-09T09:00:00Z',
    lastUpdate: '2024-07-09T09:05:00Z',
    conversation: [],
  },
];